const channelEvents = {
  STAGE_PARTICIPANT_KICKED: 'STAGE_PARTICIPANT_KICKED',
  STAGE_SESSION_HAS_ENDED: 'STAGE_SESSION_HAS_ENDED',
  STAGE_REQUEST_TO_JOIN: 'STAGE_REQUEST_TO_JOIN'
};

export default channelEvents;
