name: On Pull Request Backend Unit Testing Workflow

on:
  pull_request:
    branches: [main, feat/stages-v2]
    types: [opened, reopened, synchronize]
    paths: ['cdk/api/**']

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label }}'
  cancel-in-progress: true

jobs:
  be-unit-tests:
    name: Unit Test and Build the Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cdk/api
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node v16.x and Cache npm Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: ./cdk/api/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build and Test
        run: |
          npm run build
          npm run test
